### PR TITLE
Updates callbacks to Link V2

### PR DESCRIPTION
**Pull request by TrekSoft**
https://www.notion.so/pinwheelapi/Link-Events-External-b4ef7a25bad845b8bfa4eab0164e5cf1

### CODE REVIEW

**Review by roscioli — APPROVED** [review]
hell yeah, don't know Kotlin but looks great! where do we bump the version to 2 though?

**Comment by TrekSoft** [comment]
Ah, good point - I'll sync up with Robby on that before merging/deploying

**Comment by roscioli** [comment]
oh also are we passing in the version and the `initializationProps`?

**Comment by TrekSoft** [comment]
No I don't think so - that'd be a new thing we'll have to do.

**Review by roscioli — APPROVED** [review]

**Pull request merged**
